version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./db:/data
    ports:
      - "5000:5000"
    environment:
      - API_TOKEN=changeme
      - DB_PATH=/data/hanzi.db

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    depends_on:
      - backend

