name: hanziapp
description: A Flutter project to review hanzi.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  reorderables: ^0.6.0
  audioplayers: ^6.5.0
  google_mlkit_digital_ink_recognition: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.10.0 

flutter:
  uses-material-design: true
